"""
Inference API Wrapper for AI Smart Accident Detection System.
Wraps testing/integrated_video_test.py to execute AI model inference and return structured JSON results.
DO NOT RETRAIN OR REPLACE MODELS.
"""

import sys
import os
from pathlib import Path
import json
import uuid

ROOT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT_DIR))

# Import the existing integrated video test pipeline
from testing.integrated_video_test import run as run_integrated_test

OUTPUT_DIR = ROOT_DIR / "static" / "outputs"
UPLOADS_DIR = ROOT_DIR / "static" / "uploads"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
UPLOADS_DIR.mkdir(parents=True, exist_ok=True)

def analyze_video(input_video_path: str, camera_id: str = "C03", location: str = "NH-44 Demo Location") -> dict:
    """
    Executes the existing 3-model integrated inference pipeline on the input video.
    Returns structured results dictionary matching the frontend demo requirements.
    """
    req_id = str(uuid.uuid4())[:8]
    in_path = Path(input_video_path)
    output_video_filename = f"res_{req_id}_{in_path.stem}.mp4"
    output_video_path = OUTPUT_DIR / output_video_filename
    summary_filename = f"summary_{req_id}.txt"
    summary_path = OUTPUT_DIR / summary_filename

    # Execute the actual integrated pipeline
    run_integrated_test(
        video_path=str(input_video_path),
        output_video_path=str(output_video_path),
        summary_path=str(summary_path),
        debug=False
    )

    # Parse the summary output generated by the pipeline
    summary_data = {}
    if summary_path.exists():
        with open(summary_path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                if ":" in line and not line.startswith("="):
                    parts = line.strip().split(":", 1)
                    if len(parts) == 2:
                        k = parts[0].strip()
                        v = parts[1].strip()
                        summary_data[k] = v

    accident_detected = summary_data.get("Accident Detected", "NO") == "YES"
    accident_verified = summary_data.get("Accident Verified", "NO") == "YES"
    accident_type = summary_data.get("Accident Type", "N/A")
    severity = summary_data.get("Severity", "NO ACCIDENT")
    sev_conf_str = summary_data.get("Severity Confidence", "N/A")
    
    try:
        sev_conf = float(sev_conf_str) if sev_conf_str != "N/A" else 0.0
    except ValueError:
        sev_conf = 0.0

    avg_conf_str = summary_data.get("Average Confidence", "N/A")
    try:
        avg_conf = float(avg_conf_str) if avg_conf_str != "N/A" else 0.0
    except ValueError:
        avg_conf = 0.0

    max_conf_str = summary_data.get("Maximum Confidence", "N/A")
    try:
        max_conf = float(max_conf_str) if max_conf_str != "N/A" else 0.0
    except ValueError:
        max_conf = 0.0

    first_det = summary_data.get("First Detection", "N/A")
    conf_frame = summary_data.get("Confirmation Frame", "N/A")
    duration = summary_data.get("Duration", "N/A")

    # Relative video URL for static server
    output_video_url = f"/static/outputs/{output_video_filename}"

    return {
        "accident_detected": accident_detected,
        "accident_verified": accident_verified,
        "accident_type": accident_type,
        "severity": severity,
        "severity_confidence": round(sev_conf, 3),
        "first_detection": first_det,
        "confirmation_frame": conf_frame,
        "duration": duration,
        "average_confidence": round(avg_conf, 3),
        "maximum_confidence": round(max_conf, 3),
        "output_video": output_video_url,
        "camera_id": camera_id,
        "location": location,
        "night_traffic": {
            "Cars": summary_data.get("Cars", "N/A"),
            "Motorbikes": summary_data.get("Motorbikes", "N/A"),
            "People": summary_data.get("People", "N/A")
        }
    }
